sudo: required
dist: xenial

language:
  - cpp

matrix:
  include:
    - env:
        - BUILD_NAME=NO_MPI
        - TARGET=setsm
    - env:
        - BUILD_NAME=MPI
        - TARGET=setsm_mpi
addons:
  apt:
    packages:
    - g++
    - libtiff5-dev
    - libgeotiff-dev
    - libopenmpi-dev

before_script:
  - gcc --version
script:
  - make -f Makefile.gcc -j2 ${TARGET}

